# GitHub actions workflow to test that Python subprocess.run commands execute successfully

name: Verify Apache Installation

on: 
  push:
    branches:
       - main
    paths:
        - 'install_apache.py'

jobs:
  install_apache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apache
        run: |
          sudo apt-get update
          python3 install_apache.py


