# GitHub actions workflow to test that Python subprocess.run commands execute successfully

name: Verify Apache Installation

on: 
  push:
    paths:
      - 'install_*.py'
    branches:
       - main
  workflow_dispatch:     

jobs:
  install_apache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Adjust directory permissions
        run: sudo chown -R $USER:$USER /var/www/html/
      
      - name: Install Apache
        run: |
          sudo apt-get update
          python3 install_apache.py


